"use client"

export default function PrioritiesContent() {
  const actions = [
    {
      rank: 1,
      title: "Start PRD for AgentOps Platform",
      urgency: "High",
      type: "opportunity_pursuit",
      user: "pm-builder",
      eta: "24h ETA",
      reasoning: "Tier A epic (score 8.40) with strong strategic fit. 'Vercel for Autonomous Agents' addresses real infrastructure pain. Market timing window open. AgentOps enables all future agent work.",
      impact: "Unlock infrastructure for 10+ agent deployments. Potential $1K MRR month 6.",
      borderColor: "border-l-[#e94560]",
      badgeBg: "bg-red-500/20",
      badgeText: "text-red-400",
      badgeBg2: "bg-[#e94560]",
    },
    {
      rank: 2,
      title: "Complete Norm VPS Setup",
      urgency: "High",
      type: "blocker_resolution",
      user: "P",
      eta: "40m ETA",
      reasoning: "Task 85% complete but stalled on manual steps (DO signup, droplet creation). Automation package ready. Completing unblocks Norm's access to his own OpenClaw instance. 5-day-old task showing age.",
      impact: "Norm gains autonomous agent capability. Validates end-to-end setup automation.",
      borderColor: "border-l-yellow-500",
      badgeBg: "bg-yellow-500/20",
      badgeText: "text-yellow-400",
      badgeBg2: "bg-yellow-500",
    },
    {
      rank: 3,
      title: "Respond to CompetitorX AI Invoice Launch",
      urgency: "Medium",
      type: "incident_response",
      user: "head-of-product",
      eta: "4h ETA",
      reasoning: "CompetitorX launched AI invoice feature with high confidence. Direct threat to InvoiceAuto viability. Market intel recommends privacy-first positioning pivot. 60% feature overlap exposure.",
      impact: "Protect InvoiceAuto differentiation. Capture local-first AI trend. Prevent competitive erosion.",
      borderColor: "border-l-blue-400",
      badgeBg: "bg-blue-500/20",
      badgeText: "text-blue-400",
      badgeBg2: "bg-blue-400",
    },
  ]

  return (
    <div className="space-y-6">
      {/* Metrics Bar */}
      <div className="flex gap-4 justify-center flex-wrap mb-6">
        {[
          { value: "4.2", label: "Pressure Index" },
          { value: "0", label: "Incidents" },
          { value: "33%", label: "Capacity" },
          { value: "2", label: "Tier A Ready" },
        ].map((metric) => (
          <div key={metric.label} className="bg-white/5 px-6 py-4 rounded-lg text-center">
            <div className="text-2xl font-semibold text-[#e94560]">{metric.value}</div>
            <div className="text-xs text-gray-400 uppercase mt-1">{metric.label}</div>
          </div>
        ))}
      </div>

      {/* Pressure Bar */}
      <div className="w-full h-2 bg-white/10 rounded-full overflow-hidden mb-8">
        <div 
          className="h-full rounded-full bg-gradient-to-r from-[#0f3460] to-[#e94560] transition-all" 
          style={{ width: "42%" }} 
        />
      </div>

      {/* Actions */}
      <div className="space-y-4">
        {actions.map((action) => (
          <div
            key={action.rank}
            className={`bg-white/3 border border-white/10 rounded-xl p-6 border-l-4 ${action.borderColor} hover:bg-white/5 hover:border-[#e94560]/30 transition-all`}
          >
            <div className="flex items-center gap-3 mb-3">
              <div className={`w-7 h-7 rounded-full flex items-center justify-center text-sm font-bold text-white ${action.badgeBg2}`}>
                {action.rank}
              </div>
              <div className="flex-1 font-medium text-lg">{action.title}</div>
              <span className={`text-xs px-2 py-1 rounded uppercase font-semibold ${action.badgeBg} ${action.badgeText}`}>
                {action.urgency}
              </span>
            </div>

            <div className="flex gap-4 text-sm text-gray-400 mb-3">
              <span>📋 {action.type}</span>
              <span>👤 {action.user}</span>
              <span>⏱️ {action.eta}</span>
            </div>

            <div className="text-sm text-gray-300 leading-relaxed mb-3">
              {action.reasoning}
            </div>

            <div className="text-sm text-green-400 italic">
              💡 Impact: {action.impact}
            </div>
          </div>
        ))}
      </div>

      <div className="text-center mt-8 pt-8 border-t border-white/10 text-gray-500 text-sm">
        Generated by What Should We Do Next Engine • Consiglio or it didn't happen
      </div>
    </div>
  )
}
